### ISSUE TITLE
FLA's not containing character backgrounds.

### ISSUE THREAD

**Issue by canofspaghettios** [CryBitDev/Sonic.exe-source#6]
I was looking for the Majin Sonic background FLA but it appears to be nowhere. Not in the Majin FLA, nor any other backgrounds are included. Am I just blind, or are they actually not there?

**Comment by lautichan123** [comment]
sorry for not having the answer to your problem, but where did you get the majin sonic FLA?

**Comment by canofspaghettios** [comment]
> sorry for not having the answer to your problem, but where did you get the majin sonic FLA?

I got it from "Sonic.exe-source/art/SONIC EXE SHIZ LOL/Majin_Sonic_Assets.fla

**Comment by lautichan123** [comment]
thanks

> > sorry for not having the answer to your problem, but where did you get the majin sonic FLA?
> 
> I got it from "Sonic.exe-source/art/SONIC EXE SHIZ LOL/Majin_Sonic_Assets.fla"

thanks

**Comment by MasterEric** [comment]
> from a page or where?

https://github.com/CryBitDev/Sonic.exe-source/blob/master/art/SONIC%20EXE%20SHIZ%20LOL/Majin_Sonic_Assets.fla

**Comment by canofspaghettios** [comment]
Messaged on the artists, they stated that there is actually no background FLAs, because they were made in photoshop not flash. Feelsbad but understandable.
