### ISSUE TITLE
about Json file works

### ISSUE THREAD

**Issue by versebrik** [CryBitDev/Sonic.exe-source#9]
I dont know how the json file works :(
Can you explain to me?
For notes with 5 items, please let me know what role the 4th and 5th items doing.
ex)
![image](https://user-images.githubusercontent.com/92625749/152673765-1caac485-891c-45af-88d2-a85407da3bcb.png)

**Comment by the-funky-lad** [comment]
no

**Comment by floweywastaken** [comment]
> no

yes

**Comment by CryBitDev** [comment]
check note.hx lmao
